/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AddressWhereUniqueInput } from "../../address/base/AddressWhereUniqueInput";
import { ValidateNested, IsOptional, IsString } from "class-validator";
import { Type } from "class-transformer";
import { CuisineUpdateManyWithoutRestaurantsInput } from "./CuisineUpdateManyWithoutRestaurantsInput";
import { ReviewUpdateManyWithoutRestaurantsInput } from "./ReviewUpdateManyWithoutRestaurantsInput";
@InputType()
class RestaurantUpdateInput {
  @ApiProperty({
    required: false,
    type: () => AddressWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => AddressWhereUniqueInput)
  @IsOptional()
  @Field(() => AddressWhereUniqueInput, {
    nullable: true,
  })
  address?: AddressWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => CuisineUpdateManyWithoutRestaurantsInput,
  })
  @ValidateNested()
  @Type(() => CuisineUpdateManyWithoutRestaurantsInput)
  @IsOptional()
  @Field(() => CuisineUpdateManyWithoutRestaurantsInput, {
    nullable: true,
  })
  cuisine?: CuisineUpdateManyWithoutRestaurantsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string;

  @ApiProperty({
    required: false,
    type: () => ReviewUpdateManyWithoutRestaurantsInput,
  })
  @ValidateNested()
  @Type(() => ReviewUpdateManyWithoutRestaurantsInput)
  @IsOptional()
  @Field(() => ReviewUpdateManyWithoutRestaurantsInput, {
    nullable: true,
  })
  reviews?: ReviewUpdateManyWithoutRestaurantsInput;
}
export { RestaurantUpdateInput };
