/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { CuisineService } from "../cuisine.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { CuisineCreateInput } from "./CuisineCreateInput";
import { CuisineWhereInput } from "./CuisineWhereInput";
import { CuisineWhereUniqueInput } from "./CuisineWhereUniqueInput";
import { CuisineFindManyArgs } from "./CuisineFindManyArgs";
import { CuisineUpdateInput } from "./CuisineUpdateInput";
import { Cuisine } from "./Cuisine";
import { RestaurantFindManyArgs } from "../../restaurant/base/RestaurantFindManyArgs";
import { Restaurant } from "../../restaurant/base/Restaurant";
import { RestaurantWhereUniqueInput } from "../../restaurant/base/RestaurantWhereUniqueInput";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class CuisineControllerBase {
  constructor(
    protected readonly service: CuisineService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Cuisine",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Cuisine })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(@common.Body() data: CuisineCreateInput): Promise<Cuisine> {
    return await this.service.create({
      data: data,
      select: {
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Cuisine",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [Cuisine] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(CuisineFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<Cuisine[]> {
    const args = plainToClass(CuisineFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Cuisine",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Cuisine })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: CuisineWhereUniqueInput
  ): Promise<Cuisine | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Cuisine",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Cuisine })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: CuisineWhereUniqueInput,
    @common.Body() data: CuisineUpdateInput
  ): Promise<Cuisine | null> {
    try {
      return await this.service.update({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "Cuisine",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Cuisine })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: CuisineWhereUniqueInput
  ): Promise<Cuisine | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Restaurant",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/restaurants")
  @ApiNestedQuery(RestaurantFindManyArgs)
  async findManyRestaurants(
    @common.Req() request: Request,
    @common.Param() params: CuisineWhereUniqueInput
  ): Promise<Restaurant[]> {
    const query = plainToClass(RestaurantFindManyArgs, request.query);
    const results = await this.service.findRestaurants(params.id, {
      ...query,
      select: {
        address: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "Cuisine",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/restaurants")
  async connectRestaurants(
    @common.Param() params: CuisineWhereUniqueInput,
    @common.Body() body: RestaurantWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      restaurants: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Cuisine",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/restaurants")
  async updateRestaurants(
    @common.Param() params: CuisineWhereUniqueInput,
    @common.Body() body: RestaurantWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      restaurants: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Cuisine",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/restaurants")
  async disconnectRestaurants(
    @common.Param() params: CuisineWhereUniqueInput,
    @common.Body() body: RestaurantWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      restaurants: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
